#!/usr/bin/env perl

use strict;
use warnings;

my %params;
while (@ARGV > 0) {
   my ($param, $value) = split /=/, shift, 2;
   die unless defined $value;
   $params{$param} = $value;
}

while (<>) {
   chomp;
   my $param;
   if ((($param) = m{^(.*?)=}) && defined $params{$param}) {
      print ': ${', $param, ':=', $params{$param}, '}', "\n";
   } else {
      print $_, "\n";
   }
}
