.\" --------------------------------------
.\" Oberon System Documentation   AFB 8/90
.\" (c) University of Ulm, SAI, D-7900 Ulm
.\" --------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
'\"----------------------------------------------------------------------------
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.ne 2v
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
'\"----------------------------------------------------------------------------
'\" Is [prefix]
'\" Ic capability
'\" If procname params [rtype]
'\" Ef
'\"----------------------------------------------------------------------------
.de Is
.br
.ie \\n(.$=1 .ds iS \\$1
.el .ds iS "
.nr I1 5
.nr I2 5
.in +\\n(I1
..
.de Ic
.sp .3
.in -\\n(I1
.nr I1 5
.nr I2 2
.in +\\n(I1
.ti -\\n(I1
If
\.I \\$1
\.B IN
\.IR caps :
.br
..
.de If
.ne 3v
.sp 0.3
.ti -\\n(I2
.ie \\n(.$=3 \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2) : \\$3;
.el \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2);
.br
..
.de Ef
.in -\\n(I1
.sp 0.3
..
'\"----------------------------------------------------------------------------
'\"	Strings - made in Ulm (tm 8/87)
'\"
'\"				troff or new nroff
'ds A \(:A
'ds O \(:O
'ds U \(:U
'ds a \(:a
'ds o \(:o
'ds u \(:u
'ds s \(ss
'\"
'\"     international character support
.ds ' \h'\w'e'u*4/10'\z\(aa\h'-\w'e'u*4/10'
.ds ` \h'\w'e'u*4/10'\z\(ga\h'-\w'e'u*4/10'
.ds : \v'-0.6m'\h'(1u-(\\n(.fu%2u))*0.13m+0.06m'\z.\h'0.2m'\z.\h'-((1u-(\\n(.fu%2u))*0.13m+0.26m)'\v'0.6m'
.ds ^ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z^\h'|\\n:u'
.ds ~ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z~\h'|\\n:u'
.ds C \\k:\\h'+\\w'e'u/4u'\\v'-0.6m'\\s6v\\s0\\v'0.6m'\\h'|\\n:u'
.ds v \\k:\(ah\\h'|\\n:u'
.ds , \\k:\\h'\\w'c'u*0.4u'\\z,\\h'|\\n:u'
'\"----------------------------------------------------------------------------
.ie t .ds St "\v'.3m'\s+2*\s-2\v'-.3m'
.el .ds St *
.de cC
.IP "\fB\\$1\fP"
..
'\"----------------------------------------------------------------------------
.de Op
.TP
.SM
.ie \\n(.$=2 .BI (+|\-)\\$1 " \\$2"
.el .B (+|\-)\\$1
..
.de Mo
.TP
.SM
.BI \\$1 " \\$2"
..
'\"----------------------------------------------------------------------------
.TH ASCII 3 "Last change: 31 August 1990" "Release 0.5" "Ulm's Oberon System"
.SH NAME
ASCII \- common names for ASCII control characters
.SH SYNOPSIS
.Pg
CONST
(* control characters *)
nul = 000X;   soh = 001X;   stx = 002X;   etx = 003X;   eot = 004X;
enq = 005X;   ack = 006X;   bel = 007X;   bs  = 008X;   ht  = 009X;
nl  = 00AX;   vt  = 00BX;   np  = 00CX;   cr  = 00DX;   so  = 00EX;
si  = 00FX;   dle = 010X;   dc1 = 011X;   dc2 = 012X;   dc3 = 013X;
dc4 = 014X;   nak = 015X;   syn = 016X;   etb = 017X;   can = 018X;
em  = 019X;   sub = 01AX;   esc = 01BX;   fs  = 01CX;   gs  = 01DX;
rs  = 01EX;   us  = 01FX;   sp  = 020X;   del = 07FX;
.sp 0.7
CtrlA = 01X;  CtrlB = 02X;  CtrlC = 03X;  CtrlD = 04X;  CtrlE = 05X;
CtrlF = 06X;  CtrlG = 07X;  CtrlH = 08X;  CtrlI = 09X;  CtrlJ = 0AX;
CtrlK = 0BX;  CtrlL = 0CX;  CtrlM = 0DX;  CtrlN = 0EX;  CtrlO = 0FX;
CtrlP = 10X;  CtrlQ = 11X;  CtrlR = 12X;  CtrlS = 13X;  CtrlT = 14X;
CtrlU = 15X;  CtrlV = 16X;  CtrlW = 17X;  CtrlX = 18X;  CtrlY = 19X;
CtrlZ = 1AX;
.sp 0.7
(* other usual names *)
EOL = nl;
null = nul;
bell = bel;
tab = ht;
lf = nl;
ff = np;
quote = 22X;
.Pe
.SH DESCRIPTION
.I ASCII
is partially generated from \fI/usr/pub/ascii\fP and exports
common names for ASCII control characters.
.LP
.I CtrlA
to
.I CtrlZ
are the codes generated by pressing <CTRL> in conjunction with
"A" to "Z" on the keyboard.
.LP
.I EOL
is the local line terminator,
.I quote
has been defined because '"' is no longer valid since revised Oberon.
.SH FILES
/usr/pub/ascii
.\" ---------------------------------------------------------------------------
.\" $Id: ASCII.3,v 1.1 90/08/31 17:02:11 borchert Rel $
.\" ---------------------------------------------------------------------------
.\" $Log:	ASCII.3,v $
.\" Revision 1.1  90/08/31  17:02:11  borchert
.\" Initial revision
.\" 
.\" ---------------------------------------------------------------------------
