.\" --------------------------------------
.\" Oberon System Documentation  AFB  5/91
.\" (c) University of Ulm, SAI, D-7900 Ulm
.\" --------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
.TH Comments 3 "Oberon System"
.SH NAME
Comments \- comment stripping input filter
.SH SYNOPSIS
.Pg
CONST delimlen = 4;
TYPE Delimiter = ARRAY delimlen OF CHAR;
.sp 0.3
TYPE Syntax = POINTER TO SyntaxRec;
TYPE SyntaxRec =
   RECORD                   (* comment syntax *)
      (Objects.ObjectRec)
      start: Delimiter;     (* starts a comment *)
      inclStart: BOOLEAN;   (* belongs start to the comment? *)
      end: Delimiter;       (* ends a comment *)
      inclEnd: BOOLEAN;     (* belongs end to the comment? *)
      nested: BOOLEAN;      (* may comments be nested? *)
   END;
.sp 0.5
PROCEDURE Open(VAR s: Streams.Stream; input: Streams.Stream;
               commentSyntax: Syntax);
.Pe
.SH DESCRIPTION
.I Comments
removes comments of a given syntax from an input stream.
.LP
.I Open
returns a newly opened stream \fIs\fP for reading
which gets its input from \fIinput\fP except that all
comments are stripped off.
The comment syntax is given by \fIsyntax\fP:
comments are delimited by \fIstart\fP and \fIend\fP.
\fIinclStart\fP and \fIinclEnd\fP determine whether
the delimiters belong to the comment or not.
Comments may be nested,
if \fInested\fP is set to \fBTRUE\fP.
.LP
Two Examples:
.TS
box;
lfI | l l.
	Oberon	Bourne Shell
_
start	(*	#
inclStart	\fBTRUE\fP	\fBTRUE\fP
end	*)	\fIASCII.nl\fP
inclEnd	\fBTRUE\fP	\fBFALSE\fP
nested	\fBTRUE\fP	\fBFALSE\fP
.TE
.SH DIAGNOSTICS
Error events which are related to \fIinput\fP
are being forwarded to the event queue of \fIs\fP.
.SH "SEE ALSO"
\fIRelatedEvents(3)\fP, \fIStreams(3)\fP
.SH BUGS
There exist languages whose comment syntax is not
covered by this module, e.g. ISO-Pascal or C++.
In general, these cases can be solved by concatenating
\fIComments\fP filters.
.\" ---------------------------------------------------------------------------
.\" $Id: Comments.3,v 1.2 91/11/18 08:06:28 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log:	Comments.3,v $
.\" Revision 1.2  91/11/18  08:06:28  borchert
.\" new event handling by RelatedEvents
.\" 
.\" Revision 1.1  1991/11/05  09:26:51  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
