.\" ---------------------------------------------------------------------------
.\" Ulm's Oberon System Documentation
.\" Copyright (C) 1989-2001 by University of Ulm, SAI, D-89069 Ulm, Germany
.\" ---------------------------------------------------------------------------
.\"    Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\" 
.\"    Permission is granted to copy and distribute modified versions of
.\" this manual under the conditions for verbatim copying, provided also
.\" that the sections entitled "GNU General Public License" and "Protect
.\" Your Freedom--Fight `Look And Feel'" are included exactly as in the
.\" original, and provided that the entire resulting derived work is
.\" distributed under the terms of a permission notice identical to this
.\" one.
.\" 
.\"    Permission is granted to copy and distribute translations of this
.\" manual into another language, under the above conditions for modified
.\" versions, except that the sections entitled "GNU General Public
.\" License" and "Protect Your Freedom--Fight `Look And Feel'", and this
.\" permission notice, may be included in translations approved by the Free
.\" Software Foundation instead of in the original English.
.\" ---------------------------------------------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
'\"----------------------------------------------------------------------------
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.ne 2v
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
'\"----------------------------------------------------------------------------
'\" Is [prefix]
'\" Ic capability
'\" If procname params [rtype]
'\" Ef
'\"----------------------------------------------------------------------------
.de Is
.br
.ie \\n(.$=1 .ds iS \\$1
.el .ds iS "
.nr I1 5
.nr I2 5
.in +\\n(I1
..
.de Ic
.sp .3
.in -\\n(I1
.nr I1 5
.nr I2 2
.in +\\n(I1
.ti -\\n(I1
If
\.I \\$1
\.B IN
\.IR caps :
.br
..
.de If
.ne 3v
.sp 0.3
.ti -\\n(I2
.ie \\n(.$=3 \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2) : \\$3;
.el \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2);
.br
..
.de Ef
.in -\\n(I1
.sp 0.3
..
'\"----------------------------------------------------------------------------
'\"	Strings - made in Ulm (tm 8/87)
'\"
'\"				troff or new nroff
'ds A \(:A
'ds O \(:O
'ds U \(:U
'ds a \(:a
'ds o \(:o
'ds u \(:u
'ds s \(ss
'\"
'\"     international character support
.ds ' \h'\w'e'u*4/10'\z\(aa\h'-\w'e'u*4/10'
.ds ` \h'\w'e'u*4/10'\z\(ga\h'-\w'e'u*4/10'
.ds : \v'-0.6m'\h'(1u-(\\n(.fu%2u))*0.13m+0.06m'\z.\h'0.2m'\z.\h'-((1u-(\\n(.fu%2u))*0.13m+0.26m)'\v'0.6m'
.ds ^ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z^\h'|\\n:u'
.ds ~ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z~\h'|\\n:u'
.ds C \\k:\\h'+\\w'e'u/4u'\\v'-0.6m'\\s6v\\s0\\v'0.6m'\\h'|\\n:u'
.ds v \\k:\(ah\\h'|\\n:u'
.ds , \\k:\\h'\\w'c'u*0.4u'\\z,\\h'|\\n:u'
'\"----------------------------------------------------------------------------
.ie t .ds St "\v'.3m'\s+2*\s-2\v'-.3m'
.el .ds St *
.de cC
.IP "\fB\\$1\fP"
..
'\"----------------------------------------------------------------------------
.de Op
.TP
.SM
.ie \\n(.$=2 .BI (+|\-)\\$1 " \\$2"
.el .B (+|\-)\\$1
..
.de Mo
.TP
.SM
.BI \\$1 " \\$2"
..
'\"----------------------------------------------------------------------------
.TH FTPAuthReader 3 "Last change: 8 May 2001" "Release 0.5" "Ulm's Oberon System"
.SH NAME
FTPAuthReader \- handler of FTP authorization commands
.SH SYNOPSIS
.Pg
TYPE AuthHandlerProc =
   PROCEDURE (session: FTPSessions.Session;
              VAR message: ARRAY OF CHAR) : BOOLEAN;
.sp 0.7
PROCEDURE AddHandler(session: FTPSessions.Session;
                     handler: AuthHandlerProc);
.sp 0.7
PROCEDURE Authorized(session: FTPSessions.Session) : BOOLEAN;
PROCEDURE GetUserName(session: FTPSessions.Session;
                      VAR name: ARRAY OF CHAR);
PROCEDURE GetPassword(session: FTPSessions.Session;
                      VAR password: ARRAY OF CHAR);
.Pe
.SH DESCRIPTION
.I FTPAuthReader
provides a FTP command handler (see \fIFTPSessions(3)\fP)
that processes the FTP commands \fIFTPCommands.user\fP,
\fIFTPCommands.pass\fP, and \fIFTPCommands.acct\fP.
.LP
.I AddHandler
installs a handler for \fIsession\fP that processes the three
FTP authorization commands of RFC 959 and invokes \fIhandler\fP
as soon a user name and an associated password are provided.
\fIhandler\fP is expected to return in dependance of the
supplied credentials either \fBTRUE\fP in case of a successful
authorization or \fBFALSE\fP otherwise. A short response
text is to be stored in \fImessage\fP.
.LP
.I GetUserName
and
.I GetPassword
return the credentials transmitted earlier to the FTP commands
\fIFTPCommands.user\fP and \fIFTPCommands.pass\fP, respectively.
.LP
.I Authorized
returns \fBTRUE\fP if a user name and a password were supplied.
It does not, however, tell whether the authorization was
successful. This is indicated by the public component \fIauthorized\fP
of \fIsession\fP.
.SH DIAGNOSTICS
.I FTPAuthReader
does not generate any error events on itself. The handler
passwd to \fIAddHandler\fP is expected to relate any error events
to \fIsession\fP.
.SH "SECURITY CONSIDERATIONS"
Care should be taken to prevent secret passwords from being logged.
This is neither done by \fIFTPAuthReader\fP nor by \fIFTPLoggers(3)\fP.
.LP
The authentication handler should not reveal in its message details
of authorization failures. Instead these should, if necessary,
packaged in error events that are related to \fIsession\fP.
.LP
While \fIFTPAuthReader\fP supports multiple authorizations in
one session, it is not recommended to accept this as
other FTP command handlers are not necessarily prepared
for re-initializations. Instead it is better to run a
non-anonymous FTP service in three phases:
.IP \(bu
using a session that offers authorization commands only,
.IP \(bu
a handler that, once a user name and a password are provided,
passes the credentials to an external authority checker
which, on success, optionally performs operations
with root privileges (e.g., chroot, setgid, and setuid), and,
.IP \(bu
creating a new session
with all necessary FTP command handlers (except
for authorization commands) that should run with the
privileges associated with the credentials (hopefully not root)
given earlier.
.SH BUGS
Username and password are silently cut after 64 bytes.
.\" ---------------------------------------------------------------------------
.\" $Id: FTPAuthReader.3,v 1.1 2001/05/08 13:46:19 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: FTPAuthReader.3,v $
.\" Revision 1.1  2001/05/08 13:46:19  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
