.\" ---------------------------------------------------------------------------
.\" Ulm's Oberon System Documentation
.\" Copyright (C) 1989-1994 by University of Ulm, SAI, D-89069 Ulm, Germany
.\" ---------------------------------------------------------------------------
.\"    Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\" 
.\"    Permission is granted to copy and distribute modified versions of
.\" this manual under the conditions for verbatim copying, provided also
.\" that the sections entitled "GNU General Public License" and "Protect
.\" Your Freedom--Fight `Look And Feel'" are included exactly as in the
.\" original, and provided that the entire resulting derived work is
.\" distributed under the terms of a permission notice identical to this
.\" one.
.\" 
.\"    Permission is granted to copy and distribute translations of this
.\" manual into another language, under the above conditions for modified
.\" versions, except that the sections entitled "GNU General Public
.\" License" and "Protect Your Freedom--Fight `Look And Feel'", and this
.\" permission notice, may be included in translations approved by the Free
.\" Software Foundation instead of in the original English.
.\" ---------------------------------------------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
'\"----------------------------------------------------------------------------
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.ne 2v
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
'\"----------------------------------------------------------------------------
'\" Is [prefix]
'\" Ic capability
'\" If procname params [rtype]
'\" Ef
'\"----------------------------------------------------------------------------
.de Is
.br
.ie \\n(.$=1 .ds iS \\$1
.el .ds iS "
.nr I1 5
.nr I2 5
.in +\\n(I1
..
.de Ic
.sp .3
.in -\\n(I1
.nr I1 5
.nr I2 2
.in +\\n(I1
.ti -\\n(I1
If
\.I \\$1
\.B IN
\.IR caps :
.br
..
.de If
.ne 3v
.sp 0.3
.ti -\\n(I2
.ie \\n(.$=3 \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2) : \\$3;
.el \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2);
.br
..
.de Ef
.in -\\n(I1
.sp 0.3
..
'\"----------------------------------------------------------------------------
'\"	Strings - made in Ulm (tm 8/87)
'\"
'\"				troff or new nroff
'ds A \(:A
'ds O \(:O
'ds U \(:U
'ds a \(:a
'ds o \(:o
'ds u \(:u
'ds s \(ss
'\"
'\"     international character support
.ds ' \h'\w'e'u*4/10'\z\(aa\h'-\w'e'u*4/10'
.ds ` \h'\w'e'u*4/10'\z\(ga\h'-\w'e'u*4/10'
.ds : \v'-0.6m'\h'(1u-(\\n(.fu%2u))*0.13m+0.06m'\z.\h'0.2m'\z.\h'-((1u-(\\n(.fu%2u))*0.13m+0.26m)'\v'0.6m'
.ds ^ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z^\h'|\\n:u'
.ds ~ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z~\h'|\\n:u'
.ds C \\k:\\h'+\\w'e'u/4u'\\v'-0.6m'\\s6v\\s0\\v'0.6m'\\h'|\\n:u'
.ds v \\k:\(ah\\h'|\\n:u'
.ds , \\k:\\h'\\w'c'u*0.4u'\\z,\\h'|\\n:u'
'\"----------------------------------------------------------------------------
.ie t .ds St "\v'.3m'\s+2*\s-2\v'-.3m'
.el .ds St *
.de cC
.IP "\fB\\$1\fP"
..
'\"----------------------------------------------------------------------------
.de Op
.TP
.SM
.ie \\n(.$=2 .BI (+|\-)\\$1 " \\$2"
.el .B (+|\-)\\$1
..
.de Mo
.TP
.SM
.BI \\$1 " \\$2"
..
'\"----------------------------------------------------------------------------
.TH IndirectDisciplines 3 "Last change: 20 March 1995" "Release 0.5" "Ulm's Oberon System"
.SH NAME
IndirectDisciplines \- shared disciplines
.SH SYNOPSIS
.Pg
TYPE Object = Disciplines.Object;
TYPE ObjectRec = Disciplines.ObjectRec;
TYPE Discipline = Disciplines.Discipline;
TYPE DisciplineRec = Disciplines.DisciplineRec;
TYPE Identifier = Disciplines.Identifier;
.sp 0.7
PROCEDURE Add(object: Object; discipline: Discipline);
PROCEDURE Remove(object: Object; id: Identifier);
PROCEDURE Seek(object: Object; id: Identifier;
               VAR discipline: Discipline) : BOOLEAN;
PROCEDURE Unique() : Identifier;
.sp 0.7
PROCEDURE Forward(from, to: Object);
.Pe
.SH DESCRIPTION
Not all kinds of disciplines are valid only in the context of a specific object.
Disciplines which carries parameter sets like \fIStreamDisciplines\fP,
for instance, need not to be tied to one object only and are good
candidates for sharing.
.I IndirectDisciplines
offers all declarations of \fIDisciplines\fP and is, in fact, plug-compatible.
Thus, modules which don't care about the carrier of their disciplines
are free to use \fIIndirectDisciplines\fP instead of \fIDisciplines\fP:
.Pg
IMPORT Disciplines := IndirectDisciplines;
.Pe
.LP
.I Forward
causes all discipline related operations of \fIIndirectDisciplines\fP
for \fIfrom\fP to be forwarded to \fIto\fP:
.Tb "Remove and Seek"
.Tp Add
causes all disciplines to be added at \fIto\fP instead of \fIfrom\fP.
.Tp "Remove and Seek"
first check for the presence of the discipline at \fIfrom\fP,
and, if not present, forward the request to \fIto\fP.
.Te
Transitive connections (i.e. a chain of forwarding references) are legal.
.LP
Usually \fIForward\fP needs not to be called directly
because \fIIndirectDisciplines\fP supports \fIForwarders(3)\fP,
i.e. \fIForwarders.Forward\fP will call \fIForward\fP
implicitly.
.LP
Note that, if necessary, operations of \fIDisciplines\fP and
\fIIndirectDisciplines\fP may be freely intermixed because
\fIIndirectDisciplines\fP relies upon \fIDisciplines\fP.
.SH "SEE ALSO"
.Tb Disciplines(3)
.Tp Disciplines(3)
discipline operations without indirection
.Tp Forwarders(3)
general forwarding mechanism
.Te
.\" ---------------------------------------------------------------------------
.\" $Id: IndirectDi.3,v 1.2 1995/03/20 08:37:48 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: IndirectDi.3,v $
.\" Revision 1.2  1995/03/20  08:37:48  borchert
.\" IndirectDisciplines support now Forwarders
.\"
.\" Revision 1.1  1994/07/04  09:30:14  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
