.\" ---------------------------------------------------------------------------
.\" Ulm's Oberon System Documentation
.\" Copyright (C) 1989-1997 by University of Ulm, SAI, D-89069 Ulm, Germany
.\" ---------------------------------------------------------------------------
.\"    Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\" 
.\"    Permission is granted to copy and distribute modified versions of
.\" this manual under the conditions for verbatim copying, provided also
.\" that the sections entitled "GNU General Public License" and "Protect
.\" Your Freedom--Fight `Look And Feel'" are included exactly as in the
.\" original, and provided that the entire resulting derived work is
.\" distributed under the terms of a permission notice identical to this
.\" one.
.\" 
.\"    Permission is granted to copy and distribute translations of this
.\" manual into another language, under the above conditions for modified
.\" versions, except that the sections entitled "GNU General Public
.\" License" and "Protect Your Freedom--Fight `Look And Feel'", and this
.\" permission notice, may be included in translations approved by the Free
.\" Software Foundation instead of in the original English.
.\" ---------------------------------------------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
'\"----------------------------------------------------------------------------
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.ne 2v
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
'\"----------------------------------------------------------------------------
'\" Is [prefix]
'\" Ic capability
'\" If procname params [rtype]
'\" Ef
'\"----------------------------------------------------------------------------
.de Is
.br
.ie \\n(.$=1 .ds iS \\$1
.el .ds iS "
.nr I1 5
.nr I2 5
.in +\\n(I1
..
.de Ic
.sp .3
.in -\\n(I1
.nr I1 5
.nr I2 2
.in +\\n(I1
.ti -\\n(I1
If
\.I \\$1
\.B IN
\.IR caps :
.br
..
.de If
.ne 3v
.sp 0.3
.ti -\\n(I2
.ie \\n(.$=3 \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2) : \\$3;
.el \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2);
.br
..
.de Ef
.in -\\n(I1
.sp 0.3
..
'\"----------------------------------------------------------------------------
'\"	Strings - made in Ulm (tm 8/87)
'\"
'\"				troff or new nroff
'ds A \(:A
'ds O \(:O
'ds U \(:U
'ds a \(:a
'ds o \(:o
'ds u \(:u
'ds s \(ss
'\"
'\"     international character support
.ds ' \h'\w'e'u*4/10'\z\(aa\h'-\w'e'u*4/10'
.ds ` \h'\w'e'u*4/10'\z\(ga\h'-\w'e'u*4/10'
.ds : \v'-0.6m'\h'(1u-(\\n(.fu%2u))*0.13m+0.06m'\z.\h'0.2m'\z.\h'-((1u-(\\n(.fu%2u))*0.13m+0.26m)'\v'0.6m'
.ds ^ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z^\h'|\\n:u'
.ds ~ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z~\h'|\\n:u'
.ds C \\k:\\h'+\\w'e'u/4u'\\v'-0.6m'\\s6v\\s0\\v'0.6m'\\h'|\\n:u'
.ds v \\k:\(ah\\h'|\\n:u'
.ds , \\k:\\h'\\w'c'u*0.4u'\\z,\\h'|\\n:u'
'\"----------------------------------------------------------------------------
.ie t .ds St "\v'.3m'\s+2*\s-2\v'-.3m'
.el .ds St *
.de cC
.IP "\fB\\$1\fP"
..
'\"----------------------------------------------------------------------------
.de Op
.TP
.SM
.ie \\n(.$=2 .BI (+|\-)\\$1 " \\$2"
.el .B (+|\-)\\$1
..
.de Mo
.TP
.SM
.BI \\$1 " \\$2"
..
'\"----------------------------------------------------------------------------
.TH InetHTTPURLs 3 "Last change: 24 April 1998" "Release 0.5" "Ulm's Oberon System"
.SH NAME
InetHTTPURLs \- implementation of HTTP URLs
.SH SYNOPSIS
.Pg
TYPE URL = POINTER TO URLRec;
TYPE URLRec =
   RECORD
      (InetURLs.URLRec)
      host: Streams.Stream;
      port: Streams.Stream;
      path: Streams.Stream;
      absolutePath: BOOLEAN;
      search: Streams.Stream;
      fragment: Streams.Stream;
   END;
.sp 0.7
CONST illegalScheme = 0;
CONST expectingSlash = 1;
CONST illegalName = 2;
CONST illegalPort = 3;
CONST illegalPath = 4;
CONST illegalSearch = 5;
CONST illegalFragment = 6;
CONST errorcodes = 7;
.sp 0.3
TYPE ErrorCode = SHORTINT;
.sp 0.3
TYPE ErrorEvent = POINTER TO ErrorEventRec;
TYPE ErrorEventRec =
   RECORD
      (Events.EventRec)
      errorcode: ErrorCode;
   END;   
.sp 0.3
VAR errorMessages: ARRAY errorcodes OF Events.Message;
VAR error: Events.EventType;
.sp 0.7      
PROCEDURE Create(VAR url: InetURLs.URL);
.Pe
.SH DESCRIPTION
The module \fIInetHTTPURLs\fP implements the procedures for processing a HTTP
URL. It first expands the URL-object to the additional parts of a HTTP URL.
\fIhost\fP is the host name of the server or \fBNIL\fP if not supplied.
\fIport\fP is the specified port of the URL or \fBNIL\fP if not supplied.
\fIpath\fP contains the path of the URL or \fBNIL\fP if not supplied. If the
path is absolute (leading slash `/') \fIabsolutePath\fP is \fBTRUE\fP. If the
URL contains a parameter (split by a question mark `?' from the prefix of the
URL) it will be stored in \fIsearch\fP otherwise \fIsearch\fP will be \fBNIL\fP.
\fIfragment\fP contains a fragment part of the URL (split by a number sign `#'
from the prefix of the URL) or \fBNIL\fP if not supplied.

\fIInetHTTPURLs\fP supports relative and absolute URLs. All parts are substreams
of the assigned stream.
.PP
\fICreate\fP creates a new HTTP URL. The components remain \fBNIL\fP until a
stream is assigned by \fIInetURLs.Assign\fP.
.PP
\fIInetURLs\fP implements the procedures \fIInetURLs.Assign\fP and
\fIInetURLs.ToString\fP.
.SH DIAGNOSTICS
The following error events may be generated assigning a stream to an URL
.Tb illegalFragment
.Tp illegalScheme
Illegal Character in scheme of URL - Syntax error
.Tp expectingSlash
Expecting '/' after scheme in URL - Syntax error
.Tp illegalName
Illegal Character in domain name of URL - Syntax error
.Tp illegalPort
Illegal Character in port number of URL - Syntax error
.Tp illegalPath
Illegal Character in path of URL - Syntax error
.Tp illegalSearch
Illegal Character in parameter part of URL - Syntax error
.Tp illegalFragment
Illegal Character in fragment-part of URL - Syntax error
.Te
.SH "SEE ALSO"
.Tb InetURLs(3)
.Tp InetURLs(3)
addresses for web pages
.Tp Streams(3)
stream operations
.Te
.SH AUTHOR
Manfred Rue\*s, University of Ulm
.\" ---------------------------------------------------------------------------
.\" $Id: InetHTTPURLs.3,v 1.1 1998/04/24 17:47:33 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: InetHTTPURLs.3,v $
.\" Revision 1.1  1998/04/24  17:47:33  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
