.\" ---------------------------------------------------------------------------
.\" Ulm's Oberon System Documentation
.\" Copyright (C) 1989-1994 by University of Ulm, SAI, D-89069 Ulm, Germany
.\" ---------------------------------------------------------------------------
.\"    Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\" 
.\"    Permission is granted to copy and distribute modified versions of
.\" this manual under the conditions for verbatim copying, provided also
.\" that the sections entitled "GNU General Public License" and "Protect
.\" Your Freedom--Fight `Look And Feel'" are included exactly as in the
.\" original, and provided that the entire resulting derived work is
.\" distributed under the terms of a permission notice identical to this
.\" one.
.\" 
.\"    Permission is granted to copy and distribute translations of this
.\" manual into another language, under the above conditions for modified
.\" versions, except that the sections entitled "GNU General Public
.\" License" and "Protect Your Freedom--Fight `Look And Feel'", and this
.\" permission notice, may be included in translations approved by the Free
.\" Software Foundation instead of in the original English.
.\" ---------------------------------------------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
'\"----------------------------------------------------------------------------
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.ne 2v
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
'\"----------------------------------------------------------------------------
'\" Is [prefix]
'\" Ic capability
'\" If procname params [rtype]
'\" Ef
'\"----------------------------------------------------------------------------
.de Is
.br
.ie \\n(.$=1 .ds iS \\$1
.el .ds iS "
.nr I1 5
.nr I2 5
.in +\\n(I1
..
.de Ic
.sp .3
.in -\\n(I1
.nr I1 5
.nr I2 2
.in +\\n(I1
.ti -\\n(I1
If
\.I \\$1
\.B IN
\.IR caps :
.br
..
.de If
.ne 3v
.sp 0.3
.ti -\\n(I2
.ie \\n(.$=3 \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2) : \\$3;
.el \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2);
.br
..
.de Ef
.in -\\n(I1
.sp 0.3
..
'\"----------------------------------------------------------------------------
'\"	Strings - made in Ulm (tm 8/87)
'\"
'\"				troff or new nroff
'ds A \(:A
'ds O \(:O
'ds U \(:U
'ds a \(:a
'ds o \(:o
'ds u \(:u
'ds s \(ss
'\"
'\"     international character support
.ds ' \h'\w'e'u*4/10'\z\(aa\h'-\w'e'u*4/10'
.ds ` \h'\w'e'u*4/10'\z\(ga\h'-\w'e'u*4/10'
.ds : \v'-0.6m'\h'(1u-(\\n(.fu%2u))*0.13m+0.06m'\z.\h'0.2m'\z.\h'-((1u-(\\n(.fu%2u))*0.13m+0.26m)'\v'0.6m'
.ds ^ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z^\h'|\\n:u'
.ds ~ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z~\h'|\\n:u'
.ds C \\k:\\h'+\\w'e'u/4u'\\v'-0.6m'\\s6v\\s0\\v'0.6m'\\h'|\\n:u'
.ds v \\k:\(ah\\h'|\\n:u'
.ds , \\k:\\h'\\w'c'u*0.4u'\\z,\\h'|\\n:u'
'\"----------------------------------------------------------------------------
.ie t .ds St "\v'.3m'\s+2*\s-2\v'-.3m'
.el .ds St *
.de cC
.IP "\fB\\$1\fP"
..
'\"----------------------------------------------------------------------------
.de Op
.TP
.SM
.ie \\n(.$=2 .BI (+|\-)\\$1 " \\$2"
.el .B (+|\-)\\$1
..
.de Mo
.TP
.SM
.BI \\$1 " \\$2"
..
'\"----------------------------------------------------------------------------
.TH NamedObjects 3 "Last change: 22 July 1996" "Release 0.5" "Ulm's Oberon System"
.SH NAME
NamedObjects \- add Names(3) functionality to arbitrary objects
.SH SYNOPSIS
.Pg
TYPE Object = Services.Object;
.sp 0.3
TYPE ErrorEvent = POINTER TO ErrorEventRec;
TYPE ErrorEventRec =
   RECORD
      (Events.EventRec)
      errorcode: SHORTINT;
   END;
VAR errormsg: ARRAY errorcodes OF Events.Message;
VAR error: Events.EventType;
.sp 0.7
PROCEDURE Create(VAR node: Names.Node; object: Object);
.sp 0.3
PROCEDURE Destroy(node: Names.Node): BOOLEAN;
.sp 0.3
PROCEDURE Get(node: Names.Node; VAR object: Object;
                     errors: RelatedEvents.Object): BOOLEAN;
.sp 0.3
PROCEDURE GuardedGet(node: Names.Node; guard: Services.Type;
                     VAR object: Object;
                     errors: RelatedEvents.Object): BOOLEAN;
.Pe
.SH DESCRIPTION
.I NamedObjects
allows to supply arbitrary extensions of
.I Services.Object
with functionality of
.I Names.Node
by way of attaching filter objects.
.PP
.I Create
creates a node representing
.IR object ,
i.e., messages sent to
.I node
will reach
.IR object ,
too.
If
.I object
is
.B NIL
.I Create
creates a node representing itself.
.PP
In order not to introduce a new
termination method for the original object via
.IR Names.Destroy ,
destroy permission of
.I node
is especially restricted.
A filter object
.I node
can however be revoked with
.IR Destroy .
.PP
.I Get
assigns
.I object
the object which is represented by
.IR node .
.I GuardedGet
does the same,
but only if the object's type is an extension of
.IR guard .
.SH DIAGNOSTICS
All procedures with
.B BOOLEAN
results return
.B TRUE
on succes, otherwise
.BR FALSE .
Following error codes are implemented:
.Tb typeGuardFailure
.Tp noObject
node is not representing a named object
.Tp objectNamed
object is already represented by another node
.Tp typeGuardFailure
.I GuardedGet
failed due to type guard violation
.Te
.SH "SEE ALSO"
.Tb RelatedEvents(3)
.Tp Names(3)
abstraction for name hierarchies
.Tp Services(3)
type-independent definition of extensions
.Tp Shards(3)
abstraction for authorization protocols
.Tp RelatedEvents(3)
error event handling
.Te
.SH BUGS
Does not yet use
.IR Forwarders(3) ,
for historical reasons.
.SH AUTHOR
Martin Hasch, University of Ulm
.\" ---------------------------------------------------------------------------
.\" $Id: NamedObjects.3,v 1.1 1996/07/22 10:57:07 martin Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: NamedObjects.3,v $
.\" Revision 1.1  1996/07/22  10:57:07  martin
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
.\" Martin Hasch, Sep 1994
.\" ---------------------------------------------------------------------------
