.\" --------------------------------------
.\" Oberon System Documentation  AFB  3/92
.\" (c) University of Ulm, SAI, D-7900 Ulm
.\" --------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.ne 2v
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
.TH NeWSSysTokens 3 "Oberon System"
.SH NAME
NeWSSysTokens \- list of NeWS system tokens
.SH SYNOPSIS
.Pg
CONST numberOfTokens = 250;
CONST maxtokenlen = 21;
.sp 0.3
TYPE TokenName = ARRAY maxtokenlen + 1 OF CHAR;
TYPE SysToken =
   RECORD
      name: TokenName;
      group: SHORTINT;
      code: INTEGER;
   END;
.sp 0.3
VAR systoken: ARRAY numberOfTokens OF SysToken;
.Pe
.SH DESCRIPTION
.ds Tl /usr/openwin/include/NeWS/systokenlist
.I NeWSSysTokens
is automatically derived from \fI\*(Tl\fP
and contains the list of system tokens of the current
NeWS protocol version.
System codes may be passed in an encoded form to the
NeWS server.
.LP
\fIsystoken\fP contains all system tokens together
with their \fIgroup\fP and \fIcode\fP:
.Tb groupXXX
.Tp "group\fP \fB0\fP\fI"
one byte encoding: \fB0B0H\fP + \fIcode\fP
.Tp "group\fP \fB1\fP\fI"
two byte encoding: \fB0A6H\fP and \fIcode\fP
.Te
.SH FILES
.Tb \*(Tl
.Tp \*(Tl
original list of system tokens
.Te
.SH "SEE ALSO"
.Tb NeWS(3)
.Tp NeWS(3)
interface to the NeWS server
.Te
.SH LIBRARY
\fINeWSSysTokens\fP is part of the \fINeWS\fP-library,
i.e. \fB+lNeWS\fP must be specified for \fImmo(1)\fP.
.\" ---------------------------------------------------------------------------
.\" $Id: NeWSSysTok.3,v 1.2 1992/04/22 10:36:53 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: NeWSSysTok.3,v $
.\" Revision 1.2  1992/04/22  10:36:53  borchert
.\" LIBRARY hint added
.\"
.\" Revision 1.1  1992/03/17  07:30:25  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
