.\" --------------------------------------
.\" Oberon System Documentation   AFB 8/90
.\" (c) University of Ulm, SAI, D-7900 Ulm
.\" --------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 8
.	ft LP
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
.TH Objects 3 "Oberon System"
.SH NAME
Objects \- common base of record types
.SH SYNOPSIS
.Pg
TYPE Object = POINTER TO ObjectRec;
TYPE ObjectRec = RECORD END;
.Pe
.SH DESCRIPTION
.I ObjectRec
is an empty record and serves as common base of
all record types of the library.
.\" ---------------------------------------------------------------------------
.\" $Id: Objects.3,v 1.1 90/08/31 17:02:16 borchert Rel $
.\" ---------------------------------------------------------------------------
.\" $Log:	Objects.3,v $
.\" Revision 1.1  90/08/31  17:02:16  borchert
.\" Initial revision
.\" 
.\" ---------------------------------------------------------------------------
