.\" ---------------------------------------------------------------------------
.\" Ulm's Oberon System Documentation
.\" Copyright (C) 1989-2005 by University of Ulm, SAI, D-89069 Ulm, Germany
.\" ---------------------------------------------------------------------------
.\"    Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\" 
.\"    Permission is granted to copy and distribute modified versions of
.\" this manual under the conditions for verbatim copying, provided also
.\" that the sections entitled "GNU General Public License" and "Protect
.\" Your Freedom--Fight `Look And Feel'" are included exactly as in the
.\" original, and provided that the entire resulting derived work is
.\" distributed under the terms of a permission notice identical to this
.\" one.
.\" 
.\"    Permission is granted to copy and distribute translations of this
.\" manual into another language, under the above conditions for modified
.\" versions, except that the sections entitled "GNU General Public
.\" License" and "Protect Your Freedom--Fight `Look And Feel'", and this
.\" permission notice, may be included in translations approved by the Free
.\" Software Foundation instead of in the original English.
.\" ---------------------------------------------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
'\"----------------------------------------------------------------------------
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.ne 2v
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
'\"----------------------------------------------------------------------------
'\" Is [prefix]
'\" Ic capability
'\" If procname params [rtype]
'\" Ef
'\"----------------------------------------------------------------------------
.de Is
.br
.ie \\n(.$=1 .ds iS \\$1
.el .ds iS "
.nr I1 5
.nr I2 5
.in +\\n(I1
..
.de Ic
.sp .3
.in -\\n(I1
.nr I1 5
.nr I2 2
.in +\\n(I1
.ti -\\n(I1
If
\.I \\$1
\.B IN
\.IR caps :
.br
..
.de If
.ne 3v
.sp 0.3
.ti -\\n(I2
.ie \\n(.$=3 \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2) : \\$3;
.el \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2);
.br
..
.de Ef
.in -\\n(I1
.sp 0.3
..
'\"----------------------------------------------------------------------------
'\"	Strings - made in Ulm (tm 8/87)
'\"
'\"				troff or new nroff
'ds A \(:A
'ds O \(:O
'ds U \(:U
'ds a \(:a
'ds o \(:o
'ds u \(:u
'ds s \(ss
'\"
'\"     international character support
.ds ' \h'\w'e'u*4/10'\z\(aa\h'-\w'e'u*4/10'
.ds ` \h'\w'e'u*4/10'\z\(ga\h'-\w'e'u*4/10'
.ds : \v'-0.6m'\h'(1u-(\\n(.fu%2u))*0.13m+0.06m'\z.\h'0.2m'\z.\h'-((1u-(\\n(.fu%2u))*0.13m+0.26m)'\v'0.6m'
.ds ^ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z^\h'|\\n:u'
.ds ~ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z~\h'|\\n:u'
.ds C \\k:\\h'+\\w'e'u/4u'\\v'-0.6m'\\s6v\\s0\\v'0.6m'\\h'|\\n:u'
.ds v \\k:\(ah\\h'|\\n:u'
.ds , \\k:\\h'\\w'c'u*0.4u'\\z,\\h'|\\n:u'
'\"----------------------------------------------------------------------------
.ie t .ds St "\v'.3m'\s+2*\s-2\v'-.3m'
.el .ds St *
.de cC
.IP "\fB\\$1\fP"
..
'\"----------------------------------------------------------------------------
.de Op
.TP
.SM
.ie \\n(.$=2 .BI (+|\-)\\$1 " \\$2"
.el .B (+|\-)\\$1
..
.de Mo
.TP
.SM
.BI \\$1 " \\$2"
..
'\"----------------------------------------------------------------------------
.TH RobustRoots 3 "Last change: 28 April 2005" "Release 0.5" "Ulm's Oberon System"
.SH NAME
RobustRoots \- robust root nodes
.SH SYNOPSIS
.Pg
TYPE ImportedRoot = POINTER TO ImportedRootRec;
TYPE ImportedRootRec = RECORD (Disciplines.ObjectRec) END;
.sp 0.7
PROCEDURE Import(address: Networks.Address;
                 path: ARRAY OF CHAR;
                 auth: Shards.Lid;
                 errors: RelatedEvents.Object);
.sp 0.3
PROCEDURE ImportR(address: Networks.Address;
                  root: Names.Node;
                  path: ARRAY OF CHAR;
                  auth: Shards.Lid;
                  errors: RelatedEvents.Object);
.sp 0.3
PROCEDURE TemporaryImport(address: Networks.Address;
                          path: ARRAY OF CHAR;
                          auth: Shards.Lid;
                          errors: RelatedEvents.Object;
                          VAR import: ImportedRoot);
.sp 0.3
PROCEDURE TemporaryImportR(address: Networks.Address;
                           root: Names.Node;
                           path: ARRAY OF CHAR;
                           auth: Shards.Lid;
                           errors: RelatedEvents.Object;
                           VAR import: ImportedRoot);
.Pe
.SH DESCRIPTION
Root nodes are the roots of a particular Oberon name space. A local
root node is provided by \fINames.root\fP, representing ``/''. The
root node of a public name space served by an Oberon name server
is usually accessible through a service following the protocol of
\fINamesBootService(3)\fP. During its initialization, \fIUnixNames(3)\fP
attempts to import the root node of the local Oberon name space as
``/pub''. Likewise, Oberon name servers may maintain links to each other.
These links to root nodes are, however, fragile and cannot survive through
\fIRobustObjects(3)\fP as \fIRobustObjects(3)\fP requires a working name
space that depends on these links.
.PP
Robustness, as defined by \fIRobustObjects(3)\fP, is the ability
of a proxy object of \fIRemoteObjects(3)\fP to survive a broken
network connection or the termination of the original object.
\fIRobustRoots\fP, in contrast, does not preserve the proxy objects of
imported roots. Instead, \fIRobustRoots\fP just attempts to re-import
a terminated root object through \fINamesBootService(3)\fP and, if this
is successful, \fIRobustRoots\fP attempts to insert the new proxy object
under the given path name. If re-imports fail, new attempts are scheduled
after some delay.
.PP
Hence, \fIRobustRoots\fP does not replace \fIRobustObjects(3)\fP but
allows to tie separate name spaces reliably such that the techniques
of \fIPathConditions(3)\fP and \fIRobustObjects(3)\fP work over name
spaces that extend over multiple Oberon name servers.
.PP
A robust import relation can be easily terminated for objects imported
by \fIRobustObjects(3)\fP by terminating the proxy object.  This,
however, does not work for root nodes imported by \fIRobustRoots\fP
as \fIRobustRoots\fP would immediately attempt to re-import the root
node again.  The persistence of \fIRobustRoots\fP to re-import a root
node can be stopped by following two methods only:
.IP \(bu
A process termination is initiated through \fIProcess.Terminate\fP,
\fIProcess.TerminateSoftly\fP, or \fIProcess.Abort\fP.
.IP \(bu
The referential import object returned by \fITemporaryImport\fP or
\fITemporaryImportR\fP is terminated using \fIResources.Notify\fP.
.PP
All four import procedures take an \fIaddress\fP parameter that
is directly passed to \fINamesBootService.Import\fP. The \fIpath\fP
is interpreted by \fIPaths(3)\fP relatively to \fINames.root\fP
(\fIImport\fP and \fITemporaryImport\fP) or to the given root
(\fIImportR\fP and \fITemporaryImportR\fP). The authorization
shard \fIauth\fP is passed to \fINames.Insert\fP.
\fITemporaryImport\fP and \fITemporaryImportR\fP return a reference
object which upon termination stops all further attempts to re-import
the root node.
.SH DIAGNOSTICS
All error events during attempts to import the root node are
related to \fIerrors\fP.
.SH "SEE ALSO"
.Tb NamesBootService(3)
.Tp NamesBootService(3)
service which exports root nodes at known addresses
.Tp Names(3)
Oberon name spaces
.Tp Path(3)
interpretation of paths within Oberon name spaces
.Tp RobustObjects(3)
proxy objects that survive their original objects
.Tp UnixNames(3)
imports the root node of the local Oberon name server
.Te
.\" ---------------------------------------------------------------------------
.\" $Id: RobustRoots.3,v 1.1 2005/04/28 13:38:32 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: RobustRoots.3,v $
.\" Revision 1.1  2005/04/28 13:38:32  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
