.\" --------------------------------------
.\" Oberon System Documentation  AFB  5/91
.\" (c) University of Ulm, SAI, D-7900 Ulm
.\" --------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
.TH Suffixes 3 "Oberon System"
.SH NAME
Suffixes \- Oberon related filename suffixes
.SH SYNOPSIS
.Pg
CONST definitionSX   = ".od";
CONST moduleSX       = ".om";
CONST symfileSX      = ".sy";
CONST reffileSX      = ".r";
CONST objectSX       = ".o";
CONST archiveSX      = ".a";
CONST deflistingSX   = ".ld";
CONST modlistingSX   = ".l";
CONST symarchive     = "SYM";
CONST refarchive     = "REF";
.sp 0.3
CONST suffixlen      = 3;
.sp 0.3
CONST srcpattern     = "*.o[dm]";
.sp 0.7
VAR definitionS: ConstStrings.String;
VAR moduleS: ConstStrings.String;
VAR symfileS: ConstStrings.String;
VAR reffileS: ConstStrings.String;
VAR objectS: ConstStrings.String;
VAR archiveS: ConstStrings.String;
VAR deflistingS: ConstStrings.String;
VAR modlistingS: ConstStrings.String;
VAR symarchiveS: ConstStrings.String;
VAR refarchiveS: ConstStrings.String;
.Pe
.SH DESCRIPTION
.I Suffixes
exports the filename suffixes of Oberon related files.
All suffix strings are exported as string constants and variables of type
\fIConstStrings.String\fP.
.I suffixlen
specifies the maximal suffix inclusive the delimiting dot.
.I srcpattern
may be given to \fIScanDir\fP to examine all Oberon sources
of the current directory.
.SH "SEE ALSO"
\fIoc(1)\fP, \fIConstStrings(3)\fP, \fIScanDir(3)\fP
.\" ---------------------------------------------------------------------------
.\" $Id: Suffixes.3,v 1.1 91/06/19 15:16:20 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log:	Suffixes.3,v $
.\" Revision 1.1  91/06/19  15:16:20  borchert
.\" Initial revision
.\" 
.\" ---------------------------------------------------------------------------
