.\" --------------------------------------
.\" Oberon System Documentation  AFB  5/91
.\" (c) University of Ulm, SAI, D-7900 Ulm
.\" --------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.ne 2v
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
.TH SysConf 3 "Oberon System: Sun 3"
.SH NAME
SysConf \- configuration parameters of the Oberon System
.SH SYNOPSIS
.Pg
CONST libdir = "@LIBDIR@";
.sp 0.2
CONST compiler = "@LIBDIR@/oberon";
CONST nameOfCompiler = "oberon";
.sp 0.2
CONST assembler = "/usr/local/bin/gas";
CONST nameOfAssembler = "gas-1.36";
.sp 0.2
CONST linkeditor = "/usr/bin/ld";
CONST nameOfLinkeditor = "ld";
.sp 0.2
CONST archivist = "/usr/5bin/ar";
CONST nameOfArchivist = "ar";
CONST needRanlib = FALSE;
CONST ranlib = "/usr/bin/ranlib";
.sp 0.7
CONST version = "0.3";
CONST distributedBy = "Universitaet Ulm, SAI";
CONST distributionDate = "Wed Jun 9 16:31:25 MET DST 1993";
.sp 0.7
(* UNIX version *)
CONST targon31 = 1;
CONST sunos4 = 2;
CONST unixversion = sunos4;
.sp 0.7
(* name of environment parameters *)
CONST obpath = "OBPATH";
CONST oblib = "OBLIB";
CONST obas = "OBAS";
CONST obar = "OBAR";
CONST obld = "OBLD";
CONST obneedranlib = "OBNEEDRANLIB";
CONST obranlib = "OBRANLIB";
.sp 0.7
CONST versionstamp = 3000; (* System V only *)
.Pe
.SH DESCRIPTION
.I SysConf
is generated during the installation of the Oberon system
and contains site-specific parameters.
They are primarily intended for \fIoc(1)\fP
(where to find the compiler, assembler etc.).
.I versionstamp
is given by \fIoc(1)\fP to \fIld(1)\fP on UNIX systems with COFF-format.
.SH "SEE ALSO"
\fIoc(1)\fP
.\" ---------------------------------------------------------------------------
.\" $Id: SysConf.3,v 1.1.2.2 1993/06/12 16:53:05 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: SysConf.3,v $
.\" Revision 1.1.2.2  1993/06/12  16:53:05  borchert
.\" SysConf has been extended for the first distributed version
.\"
.\" Revision 1.1.2.1  1991/06/19  15:32:23  borchert
.\" new branch for Sun 3 version
.\"
.\" Revision 1.1  91/06/19  15:27:34  borchert
.\" Initial revision
.\" 
.\" ---------------------------------------------------------------------------
