.\" --------------------------------------
.\" Oberon System Documentation  AFB  5/91
.\" (c) University of Ulm, SAI, D-7900 Ulm
.\" --------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
'\"----------------------------------------------------------------------------
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.ne 2v
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
'\"----------------------------------------------------------------------------
'\" Is [prefix]
'\" Ic capability
'\" If procname params [rtype]
'\" Ef
'\"----------------------------------------------------------------------------
.de Is
.br
.ie \\n(.$=1 .ds iS \\$1
.el .ds iS "
.nr I1 5
.nr I2 5
.in +\\n(I1
..
.de Ic
.sp .3
.in -\\n(I1
.nr I1 5
.nr I2 2
.in +\\n(I1
.ti -\\n(I1
If
\.I \\$1
\.B IN
\.IR caps :
.br
..
.de If
.ne 3v
.sp 0.3
.ti -\\n(I2
.ie \\n(.$=3 \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2) : \\$3;
.el \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2);
.br
..
.de Ef
.in -\\n(I1
.sp 0.3
..
'\"----------------------------------------------------------------------------
'\"	Strings - made in Ulm (tm 8/87)
'\"
'\"				troff or new nroff
'ds A \(:A
'ds O \(:O
'ds U \(:U
'ds a \(:a
'ds o \(:o
'ds u \(:u
'ds s \(ss
'\"
'\"     international character support
.ds ' \h'\w'e'u*4/10'\z\(aa\h'-\w'e'u*4/10'
.ds ` \h'\w'e'u*4/10'\z\(ga\h'-\w'e'u*4/10'
.ds : \v'-0.6m'\h'(1u-(\\n(.fu%2u))*0.13m+0.06m'\z.\h'0.2m'\z.\h'-((1u-(\\n(.fu%2u))*0.13m+0.26m)'\v'0.6m'
.ds ^ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z^\h'|\\n:u'
.ds ~ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z~\h'|\\n:u'
.ds C \\k:\\h'+\\w'e'u/4u'\\v'-0.6m'\\s6v\\s0\\v'0.6m'\\h'|\\n:u'
.ds v \\k:\(ah\\h'|\\n:u'
.ds , \\k:\\h'\\w'c'u*0.4u'\\z,\\h'|\\n:u'
'\"----------------------------------------------------------------------------
.ie t .ds St "\v'.3m'\s+2*\s-2\v'-.3m'
.el .ds St *
.de cC
.IP "\fB\\$1\fP"
..
'\"----------------------------------------------------------------------------
.de Op
.TP
.SM
.ie \\n(.$=2 .BI (+|\-)\\$1 " \\$2"
.el .B (+|\-)\\$1
..
.de Mo
.TP
.SM
.BI \\$1 " \\$2"
..
'\"----------------------------------------------------------------------------
.TH SysConf 3 "Last change: 12 June 1993" "Release 0.5" "Ulm's Oberon System:  Sun 3"
.SH NAME
SysConf \- configuration parameters of the Oberon System
.SH SYNOPSIS
.Pg
CONST libdir = "/usr/local/lib/oberon";
.sp 0.2
CONST compiler = "/usr/local/lib/oberon/oberon";
CONST nameOfCompiler = "oberon";
.sp 0.2
CONST assembler = "/usr/local/bin/gas";
CONST nameOfAssembler = "gas-1.36";
.sp 0.2
CONST linkeditor = "/usr/bin/ld";
CONST nameOfLinkeditor = "ld";
.sp 0.2
CONST archivist = "/usr/5bin/ar";
CONST nameOfArchivist = "ar";
CONST needRanlib = FALSE;
CONST ranlib = "/usr/bin/ranlib";
.sp 0.7
CONST version = "0.3";
CONST distributedBy = "Universitaet Ulm, SAI";
CONST distributionDate = "Wed Jun 9 16:31:25 MET DST 1993";
.sp 0.7
(* UNIX version *)
CONST targon31 = 1;
CONST sunos4 = 2;
CONST unixversion = sunos4;
.sp 0.7
(* name of environment parameters *)
CONST obpath = "OBPATH";
CONST oblib = "OBLIB";
CONST obas = "OBAS";
CONST obar = "OBAR";
CONST obld = "OBLD";
CONST obneedranlib = "OBNEEDRANLIB";
CONST obranlib = "OBRANLIB";
.sp 0.7
CONST versionstamp = 3000; (* System V only *)
.Pe
.SH DESCRIPTION
.I SysConf
is generated during the installation of the Oberon system
and contains site-specific parameters.
They are primarily intended for \fIoc(1)\fP
(where to find the compiler, assembler etc.).
.I versionstamp
is given by \fIoc(1)\fP to \fIld(1)\fP on UNIX systems with COFF-format.
.SH "SEE ALSO"
\fIoc(1)\fP
.\" ---------------------------------------------------------------------------
.\" $Id: SysConf.3,v 1.1.2.2 1993/06/12 16:53:05 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: SysConf.3,v $
.\" Revision 1.1.2.2  1993/06/12  16:53:05  borchert
.\" SysConf has been extended for the first distributed version
.\"
.\" Revision 1.1.2.1  1991/06/19  15:32:23  borchert
.\" new branch for Sun 3 version
.\"
.\" Revision 1.1  91/06/19  15:27:34  borchert
.\" Initial revision
.\" 
.\" ---------------------------------------------------------------------------
