.\" --------------------------------------
.\" Oberon System Documentation  AFB  5/91
.\" (c) University of Ulm, SAI, D-7900 Ulm
.\" --------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
.TH SysHost 3 "Oberon System"
.SH NAME
SysHost \- get host and domain name
.SH SYNOPSIS
.Pg
PROCEDURE GetHostName(VAR hostname: ARRAY OF CHAR);
PROCEDURE GetHostID(VAR hostid: LONGINT);
PROCEDURE GetDomainName(VAR domain: ARRAY OF CHAR);
.Pe
.SH DESCRIPTION
.I GetHostName
stores the hostname into \fIhostname\fP.
.I GetHostID
returns a number which identifies uniquely a ID-PROM which resides
on the CPU board.
.I GetDomainName
returns the NIS (formerly called Yellow Pages) domain name.
This domain name is independent (and in general different)
from that of the DNS (domain name service).
.SH "SEE ALSO"
.TS
lfI l.
gethostname(2)	\fIGetHostName\fP
gethostid(2)	\fIGetHostID\fP
getdomainname(2)	\fIGetDomainName\fP
.TE
.\" ---------------------------------------------------------------------------
.\" $Id: SysHost.3,v 1.1 91/11/12 08:36:41 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log:	SysHost.3,v $
.\" Revision 1.1  91/11/12  08:36:41  borchert
.\" Initial revision
.\" 
.\" ---------------------------------------------------------------------------
