.\" --------------------------------------
.\" Oberon System Documentation  AFB  6/93
.\" (c) University of Ulm, SAI, D-7900 Ulm
.\" --------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.ne 2v
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
.TH SysSegments 3 "Oberon System"
.SH NAME
SysSegments \- registration of reserved memory areas
.SH SYNOPSIS
.Pg
TYPE Address = LONGINT;
TYPE Size = LONGINT;
TYPE Mode = SHORTINT; (* <0: growing backward; =0 fixed; >0 growing forward *)
TYPE Segment =
   RECORD
      addr: Address;
      size: Size;
      mode: Mode;
   END;
.sp 0.7
PROCEDURE Register(addr: Address; size: Size; mode: Mode);
.sp 0.3
PROCEDURE NumberOfSegments() : INTEGER;
.sp 0.3
PROCEDURE GetSegment(segmentIndex: INTEGER; VAR segment: Segment);
.Pe
.SH DESCRIPTION
.I SysSegments
allows the registration of reserved memory segments
during the runtime startup which are not free for storage allocation.
Later, these segments may be examined by the storage allocator.
.PP
A segment is given by the interval
\fB[\fP\fIaddr\fP, \fIaddr\fP\fB+\fP\fIsize\fP\fB)\fP
and the growing mode which is specified by \fImode\fP.
Usually, there should be only one growing segment:
the stack segment which is provided by the invocation environment.
.PP
.I Register
is to be called only by the runtime start and registers
the given segment.
.PP
.I NumberOfSegments
returns the number of registered segments and
.I GetSegment
allows to retrieve the segments.
Valid segment indexes range from \fB0\fP to
\fINumberOfSegments\fP\fB()-1\fP.
.PP
The current runtime start declares following segments:
.Tb 0
.Tp 0
program text and static data
.Tp 1
preallocated area for \fIStorage\fP
.Tp 2
stack of main coroutine
.Tp 3
non-accessible area at end of address space
.Te
.SH "SEE ALSO"
.Tb Storage(3)
.Tp Storage(3)
compiler interface of the storage allocator
.Te
.\" ---------------------------------------------------------------------------
.\" $Id: SysSegment.3,v 1.1 1993/06/10 13:51:06 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: SysSegment.3,v $
.\" Revision 1.1  1993/06/10  13:51:06  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
