'\" t
.\" --------------------------------------
.\" Oberon System Documentation   AFB 8/90
.\" (c) University of Ulm, SAI, D-7900 Ulm
.\" --------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
'\"----------------------------------------------------------------------------
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.ne 2v
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
'\"----------------------------------------------------------------------------
'\" Is [prefix]
'\" Ic capability
'\" If procname params [rtype]
'\" Ef
'\"----------------------------------------------------------------------------
.de Is
.br
.ie \\n(.$=1 .ds iS \\$1
.el .ds iS "
.nr I1 5
.nr I2 5
.in +\\n(I1
..
.de Ic
.sp .3
.in -\\n(I1
.nr I1 5
.nr I2 2
.in +\\n(I1
.ti -\\n(I1
If
\.I \\$1
\.B IN
\.IR caps :
.br
..
.de If
.ne 3v
.sp 0.3
.ti -\\n(I2
.ie \\n(.$=3 \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2) : \\$3;
.el \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2);
.br
..
.de Ef
.in -\\n(I1
.sp 0.3
..
'\"----------------------------------------------------------------------------
'\"	Strings - made in Ulm (tm 8/87)
'\"
'\"				troff or new nroff
'ds A \(:A
'ds O \(:O
'ds U \(:U
'ds a \(:a
'ds o \(:o
'ds u \(:u
'ds s \(ss
'\"
'\"     international character support
.ds ' \h'\w'e'u*4/10'\z\(aa\h'-\w'e'u*4/10'
.ds ` \h'\w'e'u*4/10'\z\(ga\h'-\w'e'u*4/10'
.ds : \v'-0.6m'\h'(1u-(\\n(.fu%2u))*0.13m+0.06m'\z.\h'0.2m'\z.\h'-((1u-(\\n(.fu%2u))*0.13m+0.26m)'\v'0.6m'
.ds ^ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z^\h'|\\n:u'
.ds ~ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z~\h'|\\n:u'
.ds C \\k:\\h'+\\w'e'u/4u'\\v'-0.6m'\\s6v\\s0\\v'0.6m'\\h'|\\n:u'
.ds v \\k:\(ah\\h'|\\n:u'
.ds , \\k:\\h'\\w'c'u*0.4u'\\z,\\h'|\\n:u'
'\"----------------------------------------------------------------------------
.ie t .ds St "\v'.3m'\s+2*\s-2\v'-.3m'
.el .ds St *
.de cC
.IP "\fB\\$1\fP"
..
'\"----------------------------------------------------------------------------
.de Op
.TP
.SM
.ie \\n(.$=2 .BI (+|\-)\\$1 " \\$2"
.el .B (+|\-)\\$1
..
.de Mo
.TP
.SM
.BI \\$1 " \\$2"
..
'\"----------------------------------------------------------------------------
.TH SysTermIO 3 "Last change: 17 March 1992" "Release 0.5" "Ulm's Oberon System"
.SH NAME
SysTermIO \- UNIX System V interface to the terminal driver
.SH SYNOPSIS
.Pg
(* input modes *)
CONST ignbrk = { 31 };
CONST brkint = { 30 };
CONST ignpar = { 29 };
CONST parmrk = { 28 };
CONST inpck = { 27 };
CONST istrip = { 26 };
CONST inlcr = { 25 };
CONST igncr = { 24 };
CONST icrnl = { 23 };
CONST iuclc = { 22 };
CONST ixon = { 21 };
CONST ixany = { 20 };
CONST ixoff = { 19 };
.sp 0.3
(* output modes *)
CONST opost = { 31 };
CONST olcuc = { 30 };
CONST onlcr = { 29 };
CONST ocrnl = { 28 };
CONST onocr = { 27 };
CONST onlret = { 26 };
CONST ofill = { 25 };
CONST ofdel = { 24 };
.sp 0.3
(* delays for newline *)
CONST nldly = { 23 };           (* mask *)
CONST nl0 = { };
CONST nl1 = { 23 };
.sp 0.3
(* delays for carriage return *)
CONST crdly = { 21, 22 };       (* mask *)
CONST cr0 = { };
CONST cr1 = { 22 };
CONST cr2 = { 21 };
CONST cr3 = { 21, 22 };
.sp 0.3
(* delays for tabs *)
CONST tabdly = { 19, 20 };      (* mask *)
CONST tab1 = { 20 };
CONST tab2 = { 19 };
CONST tab3 = { 19, 20 };        (* expand tabs to spaces *)
.sp 0.3
(* delays for backspaces *)
CONST bsdly = { 18 };           (* mask *)
CONST bs0 = { };
CONST bs1 = { 18 };
.sp 0.3
(* delays for vertical tabs *)
CONST vtdly = { 17 };           (* mask *)
CONST vt0 = { };
CONST vt1 = { 17 };
.sp 0.3
(* delays for form feeds *)
CONST ffdly = { 16 };
CONST ff0 = { };
CONST ff1 = { 16 };
.sp 0.3
(* control modes *)
CONST cbaud = { 28..31 };       (* mask *)
CONST b0 = {};
CONST b50 = { 31 };
CONST b75 = { 30 };
CONST b110 = { 29, 30 };
CONST b134 = { 29 };
CONST b150 = { 29, 31 };
CONST b200 = { 29, 30 };
CONST b300 = { 29..31 };
CONST b600 = { 28 };
CONST b1200 = { 28, 31 };
CONST b1800 = { 28, 30 };
CONST b2400 = { 28, 30, 31 };
CONST b4800 = { 28, 29 };
CONST b9600 = { 28, 29, 31 };
CONST exta = { 28..30 };
CONST extb = { 28..31 };
CONST csize = { 26, 27 };       (* mask *)
CONST cs5 = {};
CONST cs6 = { 27 };
CONST cs7 = { 26 };
CONST cs8 = { 26, 27 };
CONST cstopb = { 25 };
CONST cread = { 24 };
CONST parenb = { 23 };
CONST parodd = { 22 };
CONST hupcl = { 21 };
CONST clocal = { 20 };
.sp 0.3
(* line modes *)
CONST isig = { 31 };
CONST icanon = { 30 };
CONST xcase = { 29 };
CONST echo = { 28 };
CONST echoe = { 27 };
CONST echok = { 26 };
CONST echonl = { 25 };
CONST noflsh = { 24 };
.sp 0.3
(* control characters *)
CONST vintr = 0;
CONST vquit = 1;
CONST verase = 2;
CONST vkill = 3;
CONST veof = 4;
CONST veol = 5;
CONST veol2 = 6;
CONST vswtch = 7;
CONST vmin = veof; vtime = veol;
CONST controlchars = 8;
.sp 0.7
TYPE ControlChars = INTEGER; (* vintr..vswtch *)
TYPE InputModes = SET;
TYPE OutputModes = SET;
TYPE ControlModes = SET;
TYPE LineModes = SET;
TYPE TermIO =
   RECORD
      inputmodes: InputModes;
      outputmodes: OutputModes;
      controlmodes: ControlModes;
      linemodes: LineModes;
      linedisc: CHAR;
      cc: ARRAY controlchars OF CHAR;
   END;
.sp 0.7
PROCEDURE SetTermIO(fd: SysIO.File; termio: TermIO;
                    errors: RelatedEvents.Object) : BOOLEAN;
PROCEDURE GetTermIO(fd: SysIO.File; VAR termio: TermIO;
                    errors: RelatedEvents.Object) : BOOLEAN;
.sp 0.3
PROCEDURE Terminal(fd: SysIO.File) : BOOLEAN;
.sp 0.3
PROCEDURE Baudrate(termio: TermIO) : INTEGER;
.Pe
.SH DESCRIPTION
.I SetTermIO
and
.I GetTermIO
realize the
.B TCSETA
and
.B TCGETA
.IR ioctl -calls
with type conversion for Oberon.
.I Baudrate
converts the baudrate information in
.I termio
into an integer.
.I Terminal
returns
.B TRUE
if
.I fd
is associated to a terminal device.
.SH DIAGNOSTICS
.I SetTermIO
and
.I GetTermIO
return
.B FALSE
in error case (e.g.
.I fd
is not associated to a terminal device or on
invalid parameters).
Errors cause the events of
.I SysErrors(3)
to be raised.
The \fIerrors\fP parameter is passed to \fISysErrors.Raise\fP.
.SH "SEE ALSO"
.TS
lfI l.
ioctl(2)	\fIioctl\fP system call
termio(7)	\fItermio\fP interface
SysErrors(3)	error handling of failed system calls
.TE
.SH BUGS
A portable interface for terminal settings is not yet implemented.
.\" ---------------------------------------------------------------------------
.\" $Id: SysTermIO.3,v 1.3 1992/03/17 07:36:16 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: SysTermIO.3,v $
.\" Revision 1.3  1992/03/17  07:36:16  borchert
.\" errors-parameter rearranged
.\"
.\" Revision 1.2  1991/11/18  08:19:59  borchert
.\" object parameters for RelatedEvents added
.\"
.\" Revision 1.1  1990/08/31  17:02:23  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
