.\" --------------------------------------
.\" Oberon System Documentation  AFB 11/91
.\" (c) University of Ulm, SAI, D-7900 Ulm
.\" --------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
.TH Timers 3 "Oberon System"
.SH NAME
Timers \- timer queues for clocks
.SH SYNOPSIS
.Pg
TYPE Timer = POINTER TO TimerRec;
TYPE TimerRec = RECORD (Objects.ObjectRec) END;
.sp 0.7
CONST invalidTimer = 0; (* timer is no longer valid *)
CONST queueLocked = 1; (* the queue is currently locked *)
CONST badClock = 2; (* clock is unable to maintain a timer *)
CONST errorcodes = 3;
TYPE ErrorEvent = POINTER TO ErrorEventRec;
TYPE ErrorEventRec =
   RECORD
      (Events.EventRec)
      errorcode: SHORTINT;
   END;
VAR errormsg: ARRAY errorcodes OF Events.Message;
VAR error: Events.EventType;
.sp 0.7
PROCEDURE Add(clock: Clocks.Clock; time: Times.Time; event: Events.Event;
              VAR timer: Timer);
PROCEDURE Remove(timer: Timer);
PROCEDURE Schedule(clock: Clocks.Clock;
                   time: Times.Time; event: Events.Event);
.sp 0.3
PROCEDURE NextEvent(clock: Clocks.Clock; VAR time: Times.Time) : BOOLEAN;
.Pe
.SH DESCRIPTION
.I Timers
maintains multiple timers for each clock.
.I Add
causes \fIevent\fP to be raised at the given time.
Relative time measures are taken relative to the current time.
A reference to the timer is returned to allow the timer
to be removed by \fIRemove\fP.
\fISchedule\fP works like \fIAdd\fP but does not return
a reference to the timer.
.LP
.I NextEvent
returns the time of the next event in the queue of timers.
.SH DIAGNOSTICS
Errors are related to the given clock and passed to
\fIRelatedEvents\fP:
.Tb invalidTimer
.Tp invalidTimer
An invalid timer was given to \fIRemove\fP.
Timers become invalid if they have been dispatched or removed.
.Tp queueLocked
The timer queue of the clock is currently locked.
.Tp badClock
The given clock is unable to maintain a timer.
.Te
.SH "SEE ALSO"
.Tb RelatedEvents(3)
.Tp Clocks(3)
general interface for clocks
.Tp Events(3)
event handling
.Tp RelatedEvents(3)
error handling
.Tp UnixClock(3)
implementation of the system clock
.Te
.\" ---------------------------------------------------------------------------
.\" $Id: Timers.3,v 1.2 1992/03/24 09:22:22 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: Timers.3,v $
.\" Revision 1.2  1992/03/24  09:22:22  borchert
.\" SystemClock renamed to UnixClock
.\"
.\" Revision 1.1  1992/01/04  09:46:48  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
