.\" ---------------------------------------------------------------------------
.\" Ulm's Oberon System Documentation
.\" Copyright (C) 1989-2005 by University of Ulm, SAI, D-89069 Ulm, Germany
.\" ---------------------------------------------------------------------------
.\"    Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\" 
.\"    Permission is granted to copy and distribute modified versions of
.\" this manual under the conditions for verbatim copying, provided also
.\" that the sections entitled "GNU General Public License" and "Protect
.\" Your Freedom--Fight `Look And Feel'" are included exactly as in the
.\" original, and provided that the entire resulting derived work is
.\" distributed under the terms of a permission notice identical to this
.\" one.
.\" 
.\"    Permission is granted to copy and distribute translations of this
.\" manual into another language, under the above conditions for modified
.\" versions, except that the sections entitled "GNU General Public
.\" License" and "Protect Your Freedom--Fight `Look And Feel'", and this
.\" permission notice, may be included in translations approved by the Free
.\" Software Foundation instead of in the original English.
.\" ---------------------------------------------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
'\"----------------------------------------------------------------------------
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.ne 2v
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
'\"----------------------------------------------------------------------------
'\" Is [prefix]
'\" Ic capability
'\" If procname params [rtype]
'\" Ef
'\"----------------------------------------------------------------------------
.de Is
.br
.ie \\n(.$=1 .ds iS \\$1
.el .ds iS "
.nr I1 5
.nr I2 5
.in +\\n(I1
..
.de Ic
.sp .3
.in -\\n(I1
.nr I1 5
.nr I2 2
.in +\\n(I1
.ti -\\n(I1
If
\.I \\$1
\.B IN
\.IR caps :
.br
..
.de If
.ne 3v
.sp 0.3
.ti -\\n(I2
.ie \\n(.$=3 \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2) : \\$3;
.el \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2);
.br
..
.de Ef
.in -\\n(I1
.sp 0.3
..
'\"----------------------------------------------------------------------------
'\"	Strings - made in Ulm (tm 8/87)
'\"
'\"				troff or new nroff
'ds A \(:A
'ds O \(:O
'ds U \(:U
'ds a \(:a
'ds o \(:o
'ds u \(:u
'ds s \(ss
'\"
'\"     international character support
.ds ' \h'\w'e'u*4/10'\z\(aa\h'-\w'e'u*4/10'
.ds ` \h'\w'e'u*4/10'\z\(ga\h'-\w'e'u*4/10'
.ds : \v'-0.6m'\h'(1u-(\\n(.fu%2u))*0.13m+0.06m'\z.\h'0.2m'\z.\h'-((1u-(\\n(.fu%2u))*0.13m+0.26m)'\v'0.6m'
.ds ^ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z^\h'|\\n:u'
.ds ~ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z~\h'|\\n:u'
.ds C \\k:\\h'+\\w'e'u/4u'\\v'-0.6m'\\s6v\\s0\\v'0.6m'\\h'|\\n:u'
.ds v \\k:\(ah\\h'|\\n:u'
.ds , \\k:\\h'\\w'c'u*0.4u'\\z,\\h'|\\n:u'
'\"----------------------------------------------------------------------------
.ie t .ds St "\v'.3m'\s+2*\s-2\v'-.3m'
.el .ds St *
.de cC
.IP "\fB\\$1\fP"
..
'\"----------------------------------------------------------------------------
.de Op
.TP
.SM
.ie \\n(.$=2 .BI (+|\-)\\$1 " \\$2"
.el .B (+|\-)\\$1
..
.de Mo
.TP
.SM
.BI \\$1 " \\$2"
..
'\"----------------------------------------------------------------------------
.TH UnixCommandLine 3 "Last change: 23 August 2005" "Release 0.5" "Ulm's Oberon System"
.SH NAME
UnixCommandLine \- \fIArgs(3)\fP scanner for the UNIX command line
.SH SYNOPSIS
.Pg
CONST missingValue = 0;
CONST invalidValue = 1;
CONST unknownOption = 2;
CONST unexpectedArgs = 3;
CONST helpRequested = 4;
CONST errors = 5;
.sp 0.3
TYPE ErrorEvent = POINTER TO ErrorEventRec;
TYPE ErrorEventRec =
      RECORD
	 (Events.EventRec)
	 args: Args.Arguments;
	 code: SHORTINT; (* missingValue..unexpectedArgs *)
	 name: ARRAY 80 OF CHAR;
      END;
VAR error: Events.EventType;
VAR errormsg: ARRAY errors OF Events.Message;
.sp 0.7
PROCEDURE Include(scanners: Args.ScannerList; priority: Args.Priority);
.Pe
.SH DESCRIPTION
.I UnixCommandLine
provides a scanner for the \fIArgs(3)\fP module that processes
the UNIX command line on base of \fIUnixArguments(3)\fP.
.LP
.I Include
adds the scanner of this module to \fIscanners\fP with the given
priority. Multiple invocations of \fIInclude\fP for different scanner
lists are permitted. Actual scans by this module are later on triggered
by invocations of \fIArgs.Scan\fP with a scanner list that includes
this implementation.
.LP
During its initialization,
.I UnixCommandLine
includes itself to \fIArgs.systemScanners\fP at \fIArgs.highPriority\fP.
.SH DIAGNOSTICS
A command line that does not match the specification associated
with \fIargs\fP passed to \fIArgs.Scan\fP leads to error events
that are related to \fIargs\fP:
.Tb unexpectedArgs
.Tp missingValue
An option was given without an associated value.
.Tp invalidValue
An invalid value was given for an option.
.Tp unknownOption
An unknown flag or option name was used.
.Tp unexpectedArgs
More arguments than expected were found.
.Tp helpRequested
Explicit usage help is requested.
.Te
.SH EXAMPLE
.Pg
MODULE ArgsDemo;

   IMPORT Args, Conclusions, Errors, IntArgs, RelatedEvents, StringArgs,
      UnixCommandLine;

   VAR
      args: Args.Arguments;

   PROCEDURE FetchArgs(VAR args: Args.Arguments);
   BEGIN
      Args.Create(args);
      RelatedEvents.QueueEvents(args);
      Args.Define(args, "copies",  "#", IntArgs.type,    "number of copies");
      Args.Define(args, "file",    "f", StringArgs.type, "file to be printed");
      Args.Define(args, "printer", "p", StringArgs.type, "name of the printer");
      Args.Scan(args, Args.systemScanners);
      IF RelatedEvents.EventsPending(args) THEN
         Conclusions.Conclude(args, Errors.fatal, "");
      END;
   END FetchArgs;

BEGIN
   FetchArgs(args);
END ArgsDemo.
.Pe
.SH "SEE ALSO"
.Tb UnixArguments(3)
.Tp Args(3)
general abstraction for arguments and options
.Tp UnixArguments(3)
interface to the UNIX command line
.Te
.\" ---------------------------------------------------------------------------
.\" $Id: UnixCommandLine.3,v 1.1 2005/08/23 12:57:18 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: UnixCommandLine.3,v $
.\" Revision 1.1  2005/08/23 12:57:18  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
