.\" ---------------------------------------------------------------------------
.\" Ulm's Oberon System Documentation
.\" Copyright (C) 1989-2005 by University of Ulm, SAI, D-89069 Ulm, Germany
.\" ---------------------------------------------------------------------------
.\"    Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\" 
.\"    Permission is granted to copy and distribute modified versions of
.\" this manual under the conditions for verbatim copying, provided also
.\" that the sections entitled "GNU General Public License" and "Protect
.\" Your Freedom--Fight `Look And Feel'" are included exactly as in the
.\" original, and provided that the entire resulting derived work is
.\" distributed under the terms of a permission notice identical to this
.\" one.
.\" 
.\"    Permission is granted to copy and distribute translations of this
.\" manual into another language, under the above conditions for modified
.\" versions, except that the sections entitled "GNU General Public
.\" License" and "Protect Your Freedom--Fight `Look And Feel'", and this
.\" permission notice, may be included in translations approved by the Free
.\" Software Foundation instead of in the original English.
.\" ---------------------------------------------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
'\"----------------------------------------------------------------------------
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.ne 2v
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
'\"----------------------------------------------------------------------------
'\" Is [prefix]
'\" Ic capability
'\" If procname params [rtype]
'\" Ef
'\"----------------------------------------------------------------------------
.de Is
.br
.ie \\n(.$=1 .ds iS \\$1
.el .ds iS "
.nr I1 5
.nr I2 5
.in +\\n(I1
..
.de Ic
.sp .3
.in -\\n(I1
.nr I1 5
.nr I2 2
.in +\\n(I1
.ti -\\n(I1
If
\.I \\$1
\.B IN
\.IR caps :
.br
..
.de If
.ne 3v
.sp 0.3
.ti -\\n(I2
.ie \\n(.$=3 \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2) : \\$3;
.el \fI\\$1\fP: \fBPROCEDURE\fP(\\*(iS\\$2);
.br
..
.de Ef
.in -\\n(I1
.sp 0.3
..
'\"----------------------------------------------------------------------------
'\"	Strings - made in Ulm (tm 8/87)
'\"
'\"				troff or new nroff
'ds A \(:A
'ds O \(:O
'ds U \(:U
'ds a \(:a
'ds o \(:o
'ds u \(:u
'ds s \(ss
'\"
'\"     international character support
.ds ' \h'\w'e'u*4/10'\z\(aa\h'-\w'e'u*4/10'
.ds ` \h'\w'e'u*4/10'\z\(ga\h'-\w'e'u*4/10'
.ds : \v'-0.6m'\h'(1u-(\\n(.fu%2u))*0.13m+0.06m'\z.\h'0.2m'\z.\h'-((1u-(\\n(.fu%2u))*0.13m+0.26m)'\v'0.6m'
.ds ^ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z^\h'|\\n:u'
.ds ~ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z~\h'|\\n:u'
.ds C \\k:\\h'+\\w'e'u/4u'\\v'-0.6m'\\s6v\\s0\\v'0.6m'\\h'|\\n:u'
.ds v \\k:\(ah\\h'|\\n:u'
.ds , \\k:\\h'\\w'c'u*0.4u'\\z,\\h'|\\n:u'
'\"----------------------------------------------------------------------------
.ie t .ds St "\v'.3m'\s+2*\s-2\v'-.3m'
.el .ds St *
.de cC
.IP "\fB\\$1\fP"
..
'\"----------------------------------------------------------------------------
.de Op
.TP
.SM
.ie \\n(.$=2 .BI (+|\-)\\$1 " \\$2"
.el .B (+|\-)\\$1
..
.de Mo
.TP
.SM
.BI \\$1 " \\$2"
..
'\"----------------------------------------------------------------------------
.TH UnixNames 3 "Last change: 28 April 2005" "Release 0.5" "Ulm's Oberon System"
.SH NAME
UnixNames \- import the public root
.SH SYNOPSIS
.Pg
VAR errors: RelatedEvents.Object;
.sp 0.7
PROCEDURE ImportPublicRoot(errors: RelatedEvents.Object) : BOOLEAN;
.Pe
.SH DESCRIPTION
.I UnixNames
attempts to locate a public root and to insert it under the
name ``pub'' into \fINames.root\fP.
.LP
Public roots are imported by \fINamesBootService(3)\fP
and \fIRobustRoots(3)\fP
using an address specification in the format \fIfqdn\fP:\fIport\fP
where \fIfqdn\fP is a fully qualified domain name that can be
resolved using \fIDNSResolvers(3)\fP.
.LP
The address of the public root boot service can be specified
.IP \(bu
by using the environment variable \fBONS_ROOT\fP,
.IP \(bu
by defining a TXT record for the current hostname that
is returned by \fIGetFullyQualifiedHostName\fP for the
attribute ``ons'' according to RFC 1464, or by
.IP \(bu
by defining a similar TXT record for the current domain
that is returned by \fIUnixHost.GetDomainName\fP.
.LP
Note that if the enviroment variable \fBONS_ROOT\fP is given, its
contents is the only address that is tried to find the public root,
i.e. TXT record lookups for
the current hostname or the current domain will be skipped.
.LP
.I ImportPublicRoot
allows to re-import the public root in case of a termination of
the previous public root.
.SH EXAMPLE
Following TXT records specifies that the public root boot service
for the domain ``mathematik.uni-ulm.de'' is
hosted at ``thales.mathematik.uni-ulm.de'' on port 9880:
.Pg
mathematik.uni-ulm.de IN TXT "ons=thales.mathematik.uni-ulm.de:9880"
.Pe
.SH DIAGNOSTICS
The error events of the initial attempt are queued in \fIerrors\fP.
.SH ENVIRONMENT
.Tb ONS_ROOT
.Tp ONS_ROOT
specifies the address of the public root boot service
.Te
.SH "SEE ALSO"
.Tb NamesBootService(3)
.Tp IPv4NameSystems(3)
allows to import root nodes using IPv4 sockets
.Tp Names(3)
abstraction for name hierarchies
.Tp NamesBootService(3)
service which exports root nodes at known addresses
.Tp RobustRoots(3)
technique that re-imports terminated root nodes
.Te
.\" ---------------------------------------------------------------------------
.\" $Id: UnixNames.3,v 1.3 2005/04/28 13:53:36 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: UnixNames.3,v $
.\" Revision 1.3  2005/04/28 13:53:36  borchert
.\" reference to RobustRoots(3) added
.\"
.\" Revision 1.2  2004/09/20 08:41:33  borchert
.\" notice added that if ONS_ROOT is given, no other lookup
.\" will be performed
.\"
.\" Revision 1.1  2004/04/08 22:01:32  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
