.\" --------------------------------------
.\" Oberon System Documentation  AFB 11/91
.\" (c) University of Ulm, SAI, D-7900 Ulm
.\" --------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.ne 2v
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
.TH UnixFileConditions 3 "Oberon System"
.SH NAME
UnixFileConditions \- conditions for \s-2UNIX\s0 file descriptors
.SH SYNOPSIS
.Pg
(* operations *)
CONST read = StreamConditions.read;
CONST write = StreamConditions.write;
CONST exception = 2;
.sp 0.7
PROCEDURE Create(VAR condition: Conditions.Condition;
                 stream: Streams.Stream;
                 fd: SysTypes.File; operation: SHORTINT);
.sp 0.3
PROCEDURE Test(stream: Streams.Stream; fd: SysTypes.File;
               operation: SHORTINT;
               errors: RelatedEvents.Object) : BOOLEAN;
.Pe
.SH DESCRIPTION
.I UnixFileConditions
interfaces \fISysSelect(3)\fP for \fIConditions(3)\fP.
It is mainly used by file descriptor based stream implementations
which support \fIStreamConditions(3)\fP.
.LP
\fICreate\fP creates a condition which evaluates to \fBTRUE\fP
if the given file descriptor \fIfd\fP is ready for \fIoperation\fP,
i.e. the operation would not block.
Additionaly,
\fIUnixFileConditions\fP is able to check the buffering state
of \fIstream\fP (if it is non-\fBNIL\fP).
.LP
\fITest\fP performs a similar check without blocking and
relates all errors to \fIerrors\fP.
.SH "SEE ALSO"
.Tb StreamConditions(3)
.Tp Conditions(3)
general interface for conditions
.Tp StreamConditions(3)
interface for stream conditions
.Tp SysSelect(3)
system call interface for \fIselect(2)\fP
.Te
.\" ---------------------------------------------------------------------------
.\" $Id: UnixFileCo.3,v 1.2 1992/03/17 07:36:38 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: UnixFileCo.3,v $
.\" Revision 1.2  1992/03/17  07:36:38  borchert
.\" errors-parameter of Test rearranged
.\"
.\" Revision 1.1  1992/01/15  07:24:16  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
