.\" --------------------------------------
.\" Oberon System Documentation  AFB 11/91
.\" (c) University of Ulm, SAI, D-7900 Ulm
.\" --------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
.TH UnixClock 3 "Oberon System"
.SH NAME
UnixClock \- implementation of the system clock
.SH DESCRIPTION
.I UnixClock
initializes \fIClocks.system\fP to the system clock of the
\s-2UNIX\s0 operating system.
.I Clocks.system
uses \fISysTime.Alarm\fP and \fISysSignals.ALRM\fP for the timer.
.SH "SEE ALSO"
.Tb SysSignals(3)
.Tp Clocks(3)
general interface for clocks
.Tp SysSignals(3)
signal handling
.Tp SysTime(3)
interface to the necessary system calls
.Tp Timers(3)
timer queues for clocks
.Te
.\" ---------------------------------------------------------------------------
.\" $Id: UnixClock.3,v 1.3 1992/03/24 09:23:01 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: UnixClock.3,v $
.\" Revision 1.3  1992/03/24  09:23:01  borchert
.\" SystemClock renamed to UnixClock
.\"
.\" Revision 1.2  1992/01/04  09:49:42  borchert
.\" reference to Timers added
.\"
.\" Revision 1.1  1992/01/02  10:53:03  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
