.\" --------------------------------------
.\" Oberon System Documentation  AFB  3/92
.\" (c) University of Ulm, SAI, D-7900 Ulm
.\" --------------------------------------
.de Pg
.nf
.ie t \{\
.	sp 0.3v
.	ps 9
.	ft CW
.\}
.el .sp 1v
..
.de Pe
.ie t \{\
.	ps
.	ft P
.	sp 0.3v
.\}
.el .sp 1v
.fi
..
.de Tb
.br
.nr Tw \w'\\$1MMM'
.in +\\n(Twu
..
.de Te
.in -\\n(Twu
..
.de Tp
.br
.ne 2v
.in -\\n(Twu
\fI\\$1\fP
.br
.in +\\n(Twu
.sp -1
..
.TH UnixProcess 3 "Oberon System"
.SH NAME
UnixProcess \- UNIX dependent initialization of \fIProcess(3)\fP
.SH DESCRIPTION
.I UnixProcess
calls \fIProcess.Setup\fP during initialization time.
.I UnixProcess
uses the process termination and suspension procedures
of \fISysProcess(3)\fP.
Further,
.I UnixProcess
initializes \fIProcess.name\fP
(basename of the command name),
\fIProcess.indicateSuccess\fP and \fIProcess.indicateFailure\fP.
.SH "SEE ALSO"
.Tb SysProcess(3)
.Tp Process(3)
general interface for process suspension and termination
.Tp SysProcess(3)
UNIX system calls which are related to process management
.Te
.\" ---------------------------------------------------------------------------
.\" $Id: UnixProces.3,v 1.1 1992/03/25 09:43:39 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: UnixProces.3,v $
.\" Revision 1.1  1992/03/25  09:43:39  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
