--- Makefile	2005-03-24 11:49:11.000000000 +0100
+++ Makefile.gentoo	2005-04-26 21:25:10.599029984 +0200
@@ -21,13 +21,17 @@
 SrcDir := $(DestDir)/src/oberon
 InitDir := $(DestDir)/etc/init.d
 InstallPonsDir := $(InstallDir)/var/pons
+InstallCDBDDir := $(InstallDir)/var/cdbd
 InstallManDir := $(InstallDir)/man
 InstallSrcDir := $(InstallDir)/src
 InstallEtcDir := $(InstallDir)/etc
 InstallIntensityDir := $(InstallEtcDir)/intensity
 InstallVarDir := $(InstallDir)/var
 InstallInitDir := $(InstallDir)/etc/init.d
-RcFile := $(InstallDir)/rc
+TempDir := /tmp
+RcFile := $(TempDir)/80oberon
+ConfCDBD := $(TempDir)/cdbd.conf
+ConfPONS := $(TempDir)/pons.conf
 ONSRoot := 127.0.0.1:9880
 ONSPort := 127.0.0.1:9881
 CDBDPort := 127.0.0.1:9882
@@ -55,6 +59,9 @@
 .PHONY:	install
 install: installbin installman installsrc installvar installetc installrc
 
+.PHONY: installgentoo
+installgentoo: install gentooconfcdbd gentooconfpons
+
 .PHONY:	installsuse
 installsuse: install installsuseinit
 
@@ -90,8 +97,8 @@
 
 .PHONY:	installvar
 installvar:
-	mkdir -p $(PonsDir)
-	mkdir -p $(CDBDDir)
+	mkdir -p $(InstallPonsDir)
+	mkdir -p $(InstallCDBDDir)
 
 .PHONY:	installetc
 installetc:	gcintensity
@@ -140,16 +147,36 @@
 installrc:	$(RcFile)
 $(RcFile):
 	echo OBERON=$(DestDir) >$@
-	echo PATH=$(BinDir):\$$PATH >>$@
-	echo MANPATH=$(ManDir):\$$MANPATH >>$@
+	echo PATH=$(BinDir) >>$@
+	echo ROOTPATH=$(BinDir) >>$@
+	echo MANPATH=$(ManDir) >>$@
 	echo ONS_ROOT=$(ONSRoot) >>$@
 	echo ONS_PORT=$(ONSPort) >>$@
 	echo CDBD_PORT=$(CDBDPort) >>$@
 	echo CDB_BASEDIR=$(CDBDir) >>$@
 	echo CDB_AUTH=$(DBAuth) >>$@
-	echo export OBERON PATH MANPATH ONS_ROOT ONS_PORT \
-	   CDBD_PORT CDB_BASEDIR CDB_AUTH >>$@
 
+.PHONY: gentooconfcdbd
+gentooconfcdbd:		$(ConfCDBD)
+$(ConfCDBD):
+	echo BASEDIR=$(DestDir) >$@
+	echo BINDIR=$(BinDir) >>$@
+	echo CDBDDIR=$(CDBDDir) >>$@
+	echo CDBDIR=$(CDBDir) >>$@
+	echo INTENSITY=$(IntensityDir)/cdbd >>$@
+	echo PONSDIR=$(PonsDir) >>$@
+	echo ONS_ROOT=$(ONSRoot) >>$@
+	echo CDBD_PORT=$(CDBDPort) >>$@
+
+.PHONY: gentooconfpons
+gentooconfpons:		$(ConfPONS)
+$(ConfPONS):
+	echo BASEDIR=$(DestDir) >$@
+	echo BINDIR=$(BinDir) >>$@
+	echo PONSDIR=$(PonsDir) >>$@
+	echo ONS_ROOT=$(ONSRoot) >>$@
+	echo ONS_PORT=$(ONSPort) >>$@
+	
 .PHONY:	installsuseinit initdir
 installsuseinit:	initdir $(InstalledInitScripts)
 initdir:
